### ISSUE TITLE
Crear Mazo de cartas

### ISSUE THREAD

**Issue by gastonframirez** [gastonframirez/PD16#4]
Tener en cuenta las cartas de juego españolas (Si encontramos alguna forma de identificar sin poner la palabra entera - "ORO", "COPAS", "BASTO, "ESPADA" - sería mejor).

**Comment by makpar** [comment]
Se me ocurrió que capaz en vez de usar la baraja española, hagamos un cambio y usemos las de poker. Porque en ASCII estan los simbolos de las de poker y podriamos ahorrarnos de escribir "ORO",...
Ademas, las reglas del juego no cambiarian. te parece?

**Comment by gastonframirez** [comment]
@makpar Mmm, capaz en verdad podemos dejar los números (1-12) pero en vez de usar los palos de la baraja española usamos la de Poker? Digo asi queda mas parecido. Pero me da lo mismo!

**Comment by makpar** [comment]
Ah dale! Ahora lo cambio

**Comment by makpar** [comment]
Serían entonces 48 cartas más 2 comodines?

**Comment by gastonframirez** [comment]
Exacto! Si se complica mucho, hay una variante del juego que no usa comodines
